target_nodes:
  - virtual-kubelet

required_namespaces:
  - default
  - kube-system
  - interlink

timeout_multiplier: 10. 
values:
  namespace: interlink

  annotations:
    slurm-job.vk.io/flags: "--job-name=test-pod-cfg -t 2800"
    slurm-job.vk.io/image-root: "docker://" 

  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
      effect: NoSchedule

